import { d as createAstro, c as createComponent, a as renderComponent, r as renderTemplate, m as maybeRenderHead, w as renderSlot, b as addAttribute } from './astro/server_CuadZCs7.mjs';
import 'piccolore';
import { $ as $$BaseLayout } from './BaseLayout_Lb3doMJi.mjs';

const $$Astro = createAstro("https://www.xbstack.com");
const $$ToolUtilityPage = createComponent(($$result, $$props, $$slots) => {
  const Astro2 = $$result.createAstro($$Astro, $$props, $$slots);
  Astro2.self = $$ToolUtilityPage;
  const { title, seoTitle, description, keywords, eyebrow = "XBSTACK Tool", intro, chips = [], faqs = [], related = [], sideLinks = [], canonical, schemaJsonLd, lang = "zh-CN" } = Astro2.props;
  return renderTemplate`${renderComponent($$result, "BaseLayout", $$BaseLayout, { "title": seoTitle || `${title} | XBSTACK`, "description": description, "keywords": keywords, "canonical": canonical, "schemaJsonLd": schemaJsonLd, "lang": lang }, { "default": ($$result2) => renderTemplate` ${maybeRenderHead()}<section class="border-b border-[var(--xb-line)] bg-[var(--xb-surface)]"> <div class="xb-shell py-11 md:py-14"> <div class="max-w-[860px]"><h1 class="xb-title">${title}</h1><p class="xb-lead">${intro}</p>${chips.length > 0 && renderTemplate`<div class="xb-chip-row mt-5">${chips.map((chip) => renderTemplate`<span class="xb-chip">${chip}</span>`)}</div>`}</div> </div> </section> <div class="xb-shell py-9 md:py-11"> <div class="xb-hub-layout"> <main class="min-w-0"> <section id="tool" class="mb-12 scroll-mt-24"><div class="xb-divider-title"><div><h2 class="xb-h2">工具操作</h2></div></div><div class="xb-surface p-4 md:p-6">${renderSlot($$result2, $$slots["tool"])}</div></section> ${renderSlot($$result2, $$slots["after-tool"])} ${faqs.length > 0 && renderTemplate`<section id="faq" class="mt-12 scroll-mt-24"><div class="xb-divider-title"><div><div class="xb-kicker">FAQ</div><h2 class="xb-h2 mt-2">常见问题</h2></div></div><div class="border-t border-[var(--xb-line)]">${faqs.map((faq) => renderTemplate`<details class="border-b border-[var(--xb-line)] py-4"><summary class="cursor-pointer text-[13px] font-bold text-[var(--xb-ink)]">${faq.q || faq.question}</summary><p class="mt-3 pr-6 text-[11px] leading-6 text-[var(--xb-muted)]">${faq.a || faq.answer}</p></details>`)}</div></section>`} </main> <aside class="xb-side-stack"> <section class="xb-side-card"><h3>页面导航</h3><a href="#tool"><span>工具操作</span><span>→</span></a>${faqs.length > 0 && renderTemplate`<a href="#faq"><span>常见问题</span><span>→</span></a>`}<a href="/tools/"><span>全部工具</span><span>→</span></a></section> ${related.length > 0 && renderTemplate`<section class="xb-side-card"><h3>相关内容</h3>${related.map((item) => renderTemplate`<a${addAttribute(item.href, "href")}><span>${item.title}</span><span>→</span></a>`)}</section>`} ${sideLinks.length > 0 && renderTemplate`<section class="xb-side-card"><h3>相关资源</h3>${sideLinks.map((item) => renderTemplate`<a${addAttribute(item.href, "href")}><span>${item.title}</span><span>→</span></a>`)}</section>`} </aside> </div> </div> ` })}`;
}, "/Users/beijingchaoyang/MyWeb/blog/src/components/search-site/ToolUtilityPage.astro", void 0);

export { $$ToolUtilityPage as $ };
