import { c as createComponent, b as renderComponent, r as renderTemplate, m as maybeRenderHead, a as renderScript } from '../../chunks/astro/server_CVKVJgiO.mjs';
import 'piccolore';
import { $ as $$AdminLayout } from '../../chunks/AdminLayout_Bid3_Fbn.mjs';
/* empty css                                         */
export { renderers } from '../../renderers.mjs';

const $$Categories = createComponent(async ($$result, $$props, $$slots) => {
  return renderTemplate`${renderComponent($$result, "Layout", $$AdminLayout, { "title": "\u77E5\u8BC6\u67B6\u6784\u4E0E SEO \u7BA1\u7406", "data-astro-cid-gr6slsrz": true }, { "default": async ($$result2) => renderTemplate` ${maybeRenderHead()}<div class="max-w-7xl mx-auto h-[calc(100vh-160px)] flex flex-col" data-astro-cid-gr6slsrz>  <div class="flex justify-between items-center mb-8 shrink-0 animate-fadeUp" data-astro-cid-gr6slsrz> <div data-astro-cid-gr6slsrz> <div class="flex items-center gap-3 mb-2" data-astro-cid-gr6slsrz> <span class="w-1.5 h-4 bg-sky-500 rounded-full animate-pulse" data-astro-cid-gr6slsrz></span> <span class="text-[10px] font-black text-slate-700 dark:text-slate-500 uppercase tracking-[0.4em]" data-astro-cid-gr6slsrz>Structure & SEO</span> </div> <h2 class="text-3xl font-black text-white italic tracking-tighter uppercase" data-astro-cid-gr6slsrz>全站栏目架构</h2> </div> <button id="save-all-btn" class="group relative px-8 py-3 rounded-2xl bg-emerald-600 text-white font-black text-[10px] tracking-[0.2em] uppercase transition-all hover:scale-105 shadow-[0_0_30px_rgba(16,185,129,0.3)] overflow-hidden" data-astro-cid-gr6slsrz> <span class="relative z-10 flex items-center gap-2" data-astro-cid-gr6slsrz> <span class="text-lg" data-astro-cid-gr6slsrz>💾</span> 保存配置
</span> <div class="absolute inset-0 bg-gradient-to-r from-emerald-500 to-emerald-700 opacity-0 group-hover:opacity-100 transition-opacity" data-astro-cid-gr6slsrz></div> </button> </div>  <div class="flex-1 grid grid-cols-12 gap-8 min-h-0 animate-fadeUp [animation-delay:200ms]" data-astro-cid-gr6slsrz>  <div class="col-span-4 bg-slate-900/50 rounded-[30px] border border-white/5 p-6 flex flex-col overflow-hidden backdrop-blur-xl" data-astro-cid-gr6slsrz> <h3 class="text-xs font-black text-slate-700 dark:text-slate-500 uppercase tracking-widest mb-6 shrink-0" data-astro-cid-gr6slsrz>站点分类树</h3> <div id="tree-container" class="flex-1 overflow-y-auto space-y-4 pr-2 custom-scrollbar" data-astro-cid-gr6slsrz>  <div class="flex items-center justify-center h-full text-slate-600 animate-pulse text-xs font-bold" data-astro-cid-gr6slsrz>正在加载数据...</div> </div> </div>  <div class="col-span-8 bg-slate-900/80 rounded-[30px] border border-slate-200 dark:border-white/10 p-8 flex flex-col overflow-hidden relative backdrop-blur-2xl shadow-2xl" data-astro-cid-gr6slsrz>  <div class="absolute top-0 right-0 w-96 h-96 bg-sky-500/5 blur-[100px] rounded-full pointer-events-none" data-astro-cid-gr6slsrz></div> <div id="editor-empty" class="flex-1 flex flex-col items-center justify-center text-slate-600" data-astro-cid-gr6slsrz> <div class="text-6xl mb-4 opacity-20" data-astro-cid-gr6slsrz>⚙️</div> <p class="text-xs font-black uppercase tracking-widest" data-astro-cid-gr6slsrz>请选择左侧节点进行配置</p> </div> <form id="editor-form" class="hidden flex-col h-full relative z-10" data-astro-cid-gr6slsrz> <input type="hidden" id="node-path" name="path" data-astro-cid-gr6slsrz> <header class="flex items-center justify-between mb-8 shrink-0 pb-6 border-b border-white/5" data-astro-cid-gr6slsrz> <div class="flex items-center gap-4" data-astro-cid-gr6slsrz> <div id="editor-icon-preview" class="w-12 h-12 rounded-xl bg-white/5 border border-slate-200 dark:border-white/10 flex items-center justify-center text-2xl" data-astro-cid-gr6slsrz></div> <div data-astro-cid-gr6slsrz> <h3 id="editor-title-display" class="text-2xl font-black text-white italic tracking-tighter" data-astro-cid-gr6slsrz></h3> <code id="editor-slug-display" class="text-[10px] font-mono text-sky-500" data-astro-cid-gr6slsrz></code> </div> </div> <div class="flex items-center gap-2" data-astro-cid-gr6slsrz> <span class="text-[9px] font-black text-slate-600 uppercase tracking-widest px-3 py-1 rounded-full bg-slate-100 dark:bg-white/5 border border-white/5" data-astro-cid-gr6slsrz>元数据编辑器</span> </div> </header> <div class="flex-1 overflow-y-auto pr-4 custom-scrollbar space-y-8" data-astro-cid-gr6slsrz>  <section class="space-y-4" data-astro-cid-gr6slsrz> <h4 class="text-[10px] font-black text-slate-700 dark:text-slate-500 uppercase tracking-widest flex items-center gap-2" data-astro-cid-gr6slsrz> <span class="w-1 h-1 bg-sky-500 rounded-full" data-astro-cid-gr6slsrz></span> 基础信息
</h4> <div class="grid grid-cols-2 gap-4" data-astro-cid-gr6slsrz> <div data-astro-cid-gr6slsrz> <label class="block text-[9px] font-bold text-slate-600 dark:text-slate-400 mb-2 uppercase" data-astro-cid-gr6slsrz>显示名称</label> <input type="text" name="title" class="w-full bg-black/40 border border-slate-200 dark:border-white/10 rounded-xl px-4 py-3 text-xs font-bold text-white focus:border-sky-500 outline-none transition-all" placeholder="例如：技术基石" data-astro-cid-gr6slsrz> </div> <div data-astro-cid-gr6slsrz> <label class="block text-[9px] font-bold text-slate-600 dark:text-slate-400 mb-2 uppercase" data-astro-cid-gr6slsrz>图标 (Emoji)</label> <input type="text" name="icon" class="w-full bg-black/40 border border-slate-200 dark:border-white/10 rounded-xl px-4 py-3 text-xs font-bold text-white focus:border-sky-500 outline-none transition-all text-center" placeholder="⚡" data-astro-cid-gr6slsrz> </div> </div> <div data-astro-cid-gr6slsrz> <label class="block text-[9px] font-bold text-slate-600 dark:text-slate-400 mb-2 uppercase" data-astro-cid-gr6slsrz>简短描述</label> <textarea name="description" rows="2" class="w-full bg-black/40 border border-slate-200 dark:border-white/10 rounded-xl px-4 py-3 text-xs font-bold text-slate-300 focus:border-sky-500 outline-none transition-all resize-none" data-astro-cid-gr6slsrz></textarea> </div> </section>  <section class="space-y-4 pt-4 border-t border-white/5" data-astro-cid-gr6slsrz> <h4 class="text-[10px] font-black text-emerald-500 uppercase tracking-widest flex items-center gap-2" data-astro-cid-gr6slsrz> <span class="w-1 h-1 bg-emerald-500 rounded-full" data-astro-cid-gr6slsrz></span> SEO 搜索引擎优化
</h4>  <div class="bg-[#202124] p-4 rounded-xl border border-white/5 mb-4" data-astro-cid-gr6slsrz> <div class="text-[10px] text-slate-700 dark:text-slate-500 mb-2 font-mono" data-astro-cid-gr6slsrz>Google 搜索结果预览</div> <div class="truncate text-[#99c3ff] text-sm mb-0.5 cursor-pointer hover:underline" id="preview-url" data-astro-cid-gr6slsrz>https://www.xbstack.com/...</div> <div class="text-[#8ab4f8] text-lg font-medium cursor-pointer hover:underline truncate" id="preview-title" data-astro-cid-gr6slsrz>页面标题</div> <div class="text-[#bdc1c6] text-xs leading-relaxed line-clamp-2" id="preview-desc" data-astro-cid-gr6slsrz>页面描述信息...</div> </div> <div data-astro-cid-gr6slsrz> <label class="block text-[9px] font-bold text-slate-600 dark:text-slate-400 mb-2 uppercase" data-astro-cid-gr6slsrz>SEO 标题 (Meta Title) <span class="text-xs text-slate-600 ml-2" data-astro-cid-gr6slsrz>(建议 60 字以内)</span></label> <input type="text" name="seo_title" class="w-full bg-black/40 border border-emerald-500/20 rounded-xl px-4 py-3 text-xs font-bold text-white focus:border-emerald-500 outline-none transition-all" placeholder="用于搜索引擎展示的完整标题" data-astro-cid-gr6slsrz> </div> <div data-astro-cid-gr6slsrz> <label class="block text-[9px] font-bold text-slate-600 dark:text-slate-400 mb-2 uppercase" data-astro-cid-gr6slsrz>SEO 描述 (Meta Description) <span class="text-xs text-slate-600 ml-2" data-astro-cid-gr6slsrz>(建议 160 字以内)</span></label> <textarea name="seo_description" rows="3" class="w-full bg-black/40 border border-emerald-500/20 rounded-xl px-4 py-3 text-xs font-bold text-slate-300 focus:border-emerald-500 outline-none transition-all resize-none" data-astro-cid-gr6slsrz></textarea> </div> <div data-astro-cid-gr6slsrz> <label class="block text-[9px] font-bold text-slate-600 dark:text-slate-400 mb-2 uppercase" data-astro-cid-gr6slsrz>关键词 (Keywords) <span class="text-xs text-slate-600 ml-2" data-astro-cid-gr6slsrz>(英文逗号分隔)</span></label> <input type="text" name="seo_keywords" class="w-full bg-black/40 border border-emerald-500/20 rounded-xl px-4 py-3 text-xs font-bold text-slate-300 focus:border-emerald-500 outline-none transition-all" placeholder="react, astro, design..." data-astro-cid-gr6slsrz> </div> </section> </div> </form> </div> </div> </div> ${renderScript($$result2, "/Users/beijingchaoyang/MyWeb/blog/src/pages/admin/categories.astro?astro&type=script&index=0&lang.ts")}  ` })}`;
}, "/Users/beijingchaoyang/MyWeb/blog/src/pages/admin/categories.astro", void 0);

const $$file = "/Users/beijingchaoyang/MyWeb/blog/src/pages/admin/categories.astro";
const $$url = "/admin/categories/";

const _page = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
  __proto__: null,
  default: $$Categories,
  file: $$file,
  url: $$url
}, Symbol.toStringTag, { value: 'Module' }));

const page = () => _page;

export { page };
